services:
  static-web-server:
    build:
      context: ./static-web-server
      dockerfile: Dockerfile
    ports:
      - "80:80"

  api-server:
    build:
      context: ./httpserver
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
