version: '3.8'

services:
  static-web-server:
    build:
      context: ./static-web-server
      dockerfile: Dockerfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`localhost`)"
      - "traefik.http.services.static.loadbalancer.server.port=80"
    deploy:
      replicas: 3

  api-server:
    build:
      context: ./httpserver
      dockerfile: Dockerfile
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    deploy:
      replicas: 3

  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"